name: PR Container Build

on:
  pull_request:
    branches: 
      - main
env:
    GIT_URL                 : "${GITHUB_SERVER_URL}/${PSNAME}"
    TFS_ROBO_REPO           : "${GITHUB_SERVER_URL}/${GIT_ROBOCI}"
    BITBUCKET_REPO          : "${BITBUCKET_URL}/${PSNAME}"
    RoboCI_BRANCH           : "master"
    TEST_HOST_NAME          : "i2mtest11"
    VAULT_HOST              : "https://vproxy.us-east.philips-healthsuite.com/"
    VAULT_SERVICE_INSTANCE  : "fhdl-vault"
    DOCKER_REPO_URL         : "docker.na1.hsdp.io"
    DOCKER_REPO_PATH        : "client-cao-aicoe_aicoe-fhdl-dev"
    DOCKER_IMAGE_VERSION    : "1.0"
    CI                      : "true"
    EMAIL_GROUP             : "ranjan.b@philips.com"
    CF_ORG                  : "client-cao-aicoe"
    CF_SPACE                : "aicoe-fhdl-dev"
    REGION_NAME             : "us-east-1"
    API_ENDPOINT            : "https://api.cloud.pcftest.com"
    CF_API_HOST             : "api.cloud.pcftest.com"
    CF_LOGIN_HOST           : "login.cloud.pcftest.com"
    JARVERSION              : "1.0.0.1-SNAPSHOT"
    DOMAIN                  : "cloud.pcftest.com"
    REDSHIFT_STORAGE_TYPE   : "redshift-dense-storage-dev"
    REDSHIFT_ZONE_NAME      : "fhdl-redshift"
    CREATE_OR_REUSE         : "create"
    GATEWAY_PROXY           : 'http://umbrella.philips.com:80/'
    GATEWAY_PROXY_SECURE    : 'http://umbrella.philips.com:443/'

jobs:
  PR-Build:

    runs-on: [self-hosted, linux, x64, philips]
    container:
      image: docker.na1.hsdp.io/hs-daas/hsdaas:latest
      credentials:
        username: ${{ secrets.DOCREG_USERNAME }}
        password: ${{ secrets.DOCREG_PASSWORD }}

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
           chmod 755 CICD/prbuild.sh
           /bin/bash CICD/prbuild.sh
           
    - name: Sonar-Analysis
      run: |
           cd Source
           mvn sonar:sonar -Dsonar.projectKey=AI_HsDaaS -Dsonar.projectName=AI_HsDaaS -Dsonar.host.url=${{ secrets.SONARURL }} -Dsonar.login=${{ secrets.SONARTOKEN }} -Dsonar.pullrequest.key=${{ github.event.number }} -Dsonar.pullrequest.branch=${{ GITHUB.HEAD_REF }} -Dsonar.pullrequest.base=${{ GITHUB.BASE_REF }} -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} -Dsonar.qualitygate.wait=true
           
    - name: Smoke-Test
      env:
           OAUTH2_CLIENT_ID : ${{ secrets.OAUTH2_CLIENT_ID }}
           OAUTH2_CLIENT_PWD : ${{ secrets.OAUTH2_CLIENT_PWD }}
           IAM_USN : ${{ secrets.IAM_USN }}
           IAM_PWD : ${{ secrets.IAM_PWD }}
           CF_USN : ${{ secrets.CF_USN }}
           CF_PWD : ${{ secrets.CF_PWD }}
      run: |           
           chmod 777 CICD/Test_Execution.sh
           /bin/bash CICD/Test_Execution.sh SMOKETEST 

           
                    

